[package]
name = "auto-ui-transpiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "auto-ui-transpile"
path = "src/main.rs"

[dependencies]
auto-ui = { path = "../auto-ui", features = ["transpiler"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
